---
title: "CENPC Screen - Joint HCT116/TERT-RPE1 - sgRNA Epigenetics Plus - downstream_Analysis"
author: "Krishnendu Guin/ Adib Keikhosravi / Gianluca Pegoraro"
date: "August 20th 2022"
output: html_document
---

```{r}
library(tidyverse)
library(ggthemes)
library(ggrepel)
library(fs)
```

```{r, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  fig.path = 'knitr_output/',
  cache = FALSE,
  dev = c("png"),
  message = FALSE,
  warning = FALSE
)

theme_set(theme_bw())
theme_update(
  axis.text.x = element_text(
    angle = -90,
    hjust = 0,
    vjust = 0.5
  ),
  axis.text.y = element_text(hjust = 0)
)
```

```{r}
read_final_results <- function(path, glob) {
  dir_ls(path = path,
         recurse = T,
         glob = glob) %>%
    map_df(read_csv)
}

glob_path <- "*_all_genes.csv"

all_tbl <- read_final_results("input", glob_path)
```

```{r}
all_tbl_wide <- all_tbl %>% 
  pivot_wider(names_from = cell_line,
              values_from = score_area_mean:sd_spots_number_mean)

rmarkdown::paged_table(all_tbl_wide)
```

```{r}
plot_cell_lines <- function(df, 
                            x_variable, 
                            y_variable, 
                            plot_title = ""){
  df %>%
  ggplot(aes(x = {{x_variable}}, 
             y = {{y_variable}},
             color = control,
             label = marker)) +
  geom_text_repel(box.padding = 0.5,
                  max.overlaps = Inf,
                  color = "black") +
  geom_point(shape = 21) + 
  geom_smooth(method = "lm",
              color = "grey50") +
  scale_color_few(name = "Treatment") +
  xlab("z-score HCT116") +
  ylab("z-score RPE1") +
  ggtitle(plot_title)
}
```

```{r cell-n-hct116-rpe1-1}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_cell_n_HCT116 > -2.5 & score_cell_n_RPE1 > 2.5,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_cell_n_HCT116,
                y_variable = score_cell_n_RPE1,
                plot_title = "Cell Number")
```

```{r cell-n-hct116-rpe1-2}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_cell_n_HCT116 > 2 & score_cell_n_RPE1 < 2,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_cell_n_HCT116,
                y_variable = score_cell_n_RPE1,
                plot_title = "Cell Number")
```

```{r cell-n-hct116-rpe1-3}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_cell_n_HCT116 < -2.5 & score_cell_n_RPE1 > 0,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_cell_n_HCT116,
                y_variable = score_cell_n_RPE1,
                plot_title = "Cell Number")
```

```{r cell-n-hct116-rpe1-4}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_cell_n_HCT116 < -2.5 & score_cell_n_RPE1 < -2.5,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_cell_n_HCT116,
                y_variable = score_cell_n_RPE1,
                plot_title = "Cell Number")
```

```{r area-hct116-rpe1-1}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_area_mean_HCT116 >  2.5 & score_area_mean_RPE1 > 2.5,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_area_mean_HCT116,
                y_variable = score_area_mean_RPE1,
                plot_title = "Nucleus Area")
```

```{r area-hct116-rpe1-2}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_area_mean_HCT116 <  3 & score_area_mean_RPE1 > 3,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_area_mean_HCT116,
                y_variable = score_area_mean_RPE1,
                plot_title = "Nucleus Area")
```

```{r area-hct116-rpe1-3}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_area_mean_HCT116 <  5 & score_area_mean_RPE1 < -2.5,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_area_mean_HCT116,
                y_variable = score_area_mean_RPE1,
                plot_title = "Nucleus Area")
```

```{r spots-n-hct116-rpe1-1}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_spots_number_mean_HCT116 < -5 & score_spots_number_mean_RPE1 < -5 
                         ,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_spots_number_mean_HCT116,
                y_variable = score_spots_number_mean_RPE1,
                plot_title = "Number of CENPC Spots")
```

```{r spots-n-hct116-rpe1-2}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_spots_number_mean_HCT116 > 2.5 & score_spots_number_mean_RPE1 > -10,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_spots_number_mean_HCT116,
                y_variable = score_spots_number_mean_RPE1,
                plot_title = "Number of CENPC Spots")
```

```{r k-corr-perc--hct116-rpe1-1}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_k_corr_perc_mean_HCT116 > 3 & score_k_corr_perc_mean_RPE1 > 3,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_k_corr_perc_mean_HCT116,
                y_variable = score_k_corr_perc_mean_RPE1,
                plot_title = "Percentage of K Function above Poisson")
```

```{r k-corr-perc--hct116-rpe1-2}
all_tbl_wide %>%
  mutate(marker = ifelse(control == "sample" & score_k_corr_perc_mean_HCT116 < -3 & score_k_corr_perc_mean_RPE1 < -2.5,
                         gene_symbol,
                         "")) %>%
plot_cell_lines(x_variable = score_k_corr_perc_mean_HCT116,
                y_variable = score_k_corr_perc_mean_RPE1,
                plot_title = "Percentage of K Function above Poisson")
```

Document the information about the analysis session

```{r sessionInfo, results='markup'}
sessionInfo()
```
